name: PR Review Assignment

on:
  pull_request_target:

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Assign/Remove reviewers based on size label
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          LABELS=$(gh pr view $PR_NUMBER --json labels --jq '.labels[].name')
          REVIEWERS="${{ github.repository_owner }}/translators"

          if [[ $LABELS == *"size/XS"* ]] || [[ $LABELS != *"size/"* ]]; then
            # Assuming 'webdoky/translators' is a team reviewer
            gh api repos/${{ github.repository_owner }}/${{ github.repository }}/pulls/$PR_NUMBER/requested_reviewers -X DELETE -f team_reviewers=$REVIEWERS
          else
            gh pr review $PR_NUMBER --add-reviewer $REVIEWERS
          fi
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
